-- CreateTable
CREATE TABLE `Account` (
    `id` VARCHAR(191) NOT NULL,
    `unification_account_id` VARCHAR(191) NULL,
    `last_name` VARCHAR(191) NULL,
    `first_name` VARCHAR(191) NULL,
    `email_receive_flag` VARCHAR(191) NULL DEFAULT '1',
    `portal_data_url` VARCHAR(191) NULL,
    `category_id` VARCHAR(191) NULL,
    `registration_name` VARCHAR(191) NOT NULL,
    `account_type_id` VARCHAR(191) NOT NULL,
    `cognito_id` VARCHAR(191) NULL,
    `mail_address` VARCHAR(191) NOT NULL,
    `lock_flg` BOOLEAN NOT NULL DEFAULT false,
    `login_date` DATETIME(3) NULL,
    `logout_date` DATETIME(3) NULL,
    `management_keywords` VARCHAR(191) NULL,
    `staff_department` VARCHAR(191) NULL,
    `staff_position` VARCHAR(191) NULL,
    `staff_last_name` VARCHAR(191) NULL,
    `staff_first_name` VARCHAR(191) NULL,
    `staff_prefecture` VARCHAR(191) NULL,
    `staff_city` VARCHAR(191) NULL,
    `staff_address` VARCHAR(191) NULL,
    `staff_building` VARCHAR(191) NULL,
    `staff_room_number` VARCHAR(191) NULL,
    `staff_tel` VARCHAR(191) NULL,
    `staff_mobile` VARCHAR(191) NULL,
    `deleted_at` DATETIME(3) NULL,
    `created_account_id` VARCHAR(191) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_account_id` VARCHAR(191) NOT NULL,
    `updated_at` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
